export default [
    {
        id:0,
        name:"Tomato",
        path:"005-tomato.svg"
    },
    {
        id:1,
        name:"Garlic",
        path:"006-garlic.svg"
    },
    {
        id:2,
        name:"Paprika",
        path:"007-paprika.svg"
    },
    {
        id:3,
        name:"Chicken",
        path:"chicken.svg"
    },
    {
        id:4,
        name:"Green beans",
        path:"greenbeans.svg"
    },
    {
        id:5,
        name:"Rabbit",
        path:"rabbit.svg"
    },
    {
        id:6,
        name:"Saffron",
        path:"saffron.svg"
    },
    {
        id:7,
        name:"White beans",
        path:"whitebeans.svg"
    }
];