export default [
    {
        id:0,
        name:"Tomato",
        path:"005-tomato.svg"
    },
    {
        id:1,
        name:"Garlic",
        path:"006-garlic.svg"
    },
    {
        id:2,
        name:"Paprika",
        path:"007-paprika.svg"
    },
    {
        id:3,
        name:"Chicken",
        path:"chicken.svg"
    },
    {
        id:4,
        name:"Green beans",
        path:"greenbeans.svg"
    },
    {
        id:5,
        name:"Rabbit",
        path:"rabbit.svg"
    },
    {
        id:6,
        name:"Saffron",
        path:"saffron.svg"
    },
    {
        id:7,
        name:"White beans",
        path:"whitebeans.svg"
    },
    {
        id:8,
        name:"Chorizo",
        path:"001-chorizo.svg"
    },
    {
        id:9,
        name:"Ham",
        path:"002-ham.svg"
    },
    {
        id:10,
        name:"Steak",
        path:"003-steak.svg"
    },
    {
        id:11,
        name:"Pineapple",
        path:"004-pineapple.svg"
    },
    {
        id:12,
        name:"Cheese",
        path:"005-cheese.svg"
    },
    {
        id:13,
        name:"Salami",
        path:"006-salami.svg"
    },
    {
        id:14,
        name:"Pepperoni",
        path:"007-pepperoni.svg"
    },
    {
        id:15,
        name:"Salmon",
        path:"008-salmon.svg"
    }
    

];